[package]
name = "illogical-control-wire"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
illogical-e2e = { version = "0.25.0", path = "../e2e" }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"

[dev-dependencies]
serde_urlencoded = "0.7.1"

[lints]
workspace = true
