[package]
name = "illogical-vt"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
libghostty-vt = { git = "https://github.com/Uzaaft/libghostty-rs.git", rev = "8953a74" }
regex = "1.13.1"
zstd = "0.14.0"

[lints]
workspace = true

[dev-dependencies]
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
