name: Feature request
description: Something illogical should do.
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: What you're trying to do
      description: The problem, not the solution. What's hard today?
    validations:
      required: true
  - type: textarea
    id: idea
    attributes:
      label: What would help
